from PyQt5.QtCore import QSize, Qt, QMetaObject
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import (QDialog, QHBoxLayout, QTabWidget, QVBoxLayout, QPushButton,
                             QFormLayout, QListWidget, QLabel, QFrame, QLineEdit,
                             QFontComboBox, QSpinBox, QSizePolicy, QWidget)


class Settingdialog(QDialog):
    def __init__(self, sb=QFont(), le=QFont(), lb=QFont(), rlw=QFont(), clw=QFont(), btn=QFont()):
        super().__init__()
        self.forw = "F"
        self.back = "B"
        self.left = "L"
        self.righ = "R"
        self.vfor = "V"
        self.vbac = "N"
        self.colb = "C"
        self.scvr = "S"
        self.circ = "E"
        self.tria = "T"
        self.fnt_for_sb = sb
        self.fnt_for_le = le
        self.fnt_for_lb = lb
        self.fnt_fr_rlw = rlw
        self.fnt_fr_clw = clw
        self.fnt_fr_btn = btn
        self.resize(640, 480)
        self.verticalLayout = QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.tabWidget = QTabWidget(self)
        self.tab_1 = QWidget()
        self.verticalLayout_2 = QVBoxLayout(self.tab_1)
        self.formLayout = QFormLayout()
        self.formLayout.setLabelAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.formLayout.setVerticalSpacing(0)
        self.spinBox = QSpinBox(self.tab_1)
        self.spinBox.setEnabled(True)
        sizepolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizepolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizepolicy)
        self.spinBox.setMinimumSize(QSize(256, 40))
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.spinBox)
        self.lineEdit = QLineEdit(self.tab_1)
        sizepolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizepolicy)
        self.lineEdit.setMinimumSize(QSize(256, 40))
        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.lineEdit)
        self.listWidget = QListWidget(self.tab_1)
        sizepolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Ignored)
        sizepolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizepolicy)
        self.listWidget.setMinimumSize(QSize(0, 40))
        self.listWidget.setFocusPolicy(Qt.NoFocus)
        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.listWidget)
        self.listWidget_2 = QListWidget(self.tab_1)
        sizepolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Ignored)
        sizepolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizepolicy)
        self.listWidget_2.setMinimumSize(QSize(0, 40))
        self.listWidget_2.setFocusPolicy(Qt.NoFocus)
        self.listWidget_2.setAutoScrollMargin(8)
        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.listWidget_2)
        self.Button = QPushButton(self.tab_1)
        sizepolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizepolicy.setHeightForWidth(self.Button.sizePolicy().hasHeightForWidth())
        self.Button.setSizePolicy(sizepolicy)
        self.Button.setMinimumSize(QSize(256, 40))
        self.Button.setFocusPolicy(Qt.NoFocus)
        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.Button)
        self.label = QLabel(self.tab_1)
        self.label.setMinimumSize(QSize(256, 40))
        self.label.setFrameShape(QFrame.Panel)
        self.label.setAlignment(Qt.AlignCenter)
        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.fontCB_3 = QFontComboBox(self.tab_1)
        self.fontCB_3.setMinimumSize(QSize(0, 40))
        self.horizontalLayout_2.addWidget(self.fontCB_3)
        self.font_sb3 = QSpinBox(self.tab_1)
        self.font_sb3.setMinimumSize(QSize(60, 40))
        self.font_sb3.setMinimum(1)
        self.font_sb3.setMaximum(50)
        self.font_sb3.setProperty("value", 8)
        self.horizontalLayout_2.addWidget(self.font_sb3)
        self.formLayout.setLayout(2, QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.fontCB_4 = QFontComboBox(self.tab_1)
        sizepolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizepolicy.setHeightForWidth(self.fontCB_4.sizePolicy().hasHeightForWidth())
        self.fontCB_4.setSizePolicy(sizepolicy)
        self.fontCB_4.setMinimumSize(QSize(0, 40))
        self.horizontalLayout_3.addWidget(self.fontCB_4)
        self.font_sb4 = QSpinBox(self.tab_1)
        sizepolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizepolicy.setHeightForWidth(self.font_sb4.sizePolicy().hasHeightForWidth())
        self.font_sb4.setSizePolicy(sizepolicy)
        self.font_sb4.setMinimumSize(QSize(60, 40))
        self.font_sb4.setMinimum(1)
        self.font_sb4.setMaximum(50)
        self.font_sb4.setProperty("value", 9)
        self.horizontalLayout_3.addWidget(self.font_sb4)
        self.formLayout.setLayout(3, QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.fontCB_2 = QFontComboBox(self.tab_1)
        self.fontCB_2.setMinimumSize(QSize(0, 40))
        self.horizontalLayout_4.addWidget(self.fontCB_2)
        self.font_sb2 = QSpinBox(self.tab_1)
        self.font_sb2.setMinimumSize(QSize(60, 40))
        self.font_sb2.setMinimum(1)
        self.font_sb2.setMaximum(50)
        self.font_sb2.setProperty("value", 8)
        self.horizontalLayout_4.addWidget(self.font_sb2)
        self.formLayout.setLayout(1, QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setSpacing(5)
        self.fontCB_1 = QFontComboBox(self.tab_1)
        self.fontCB_1.setMinimumSize(QSize(0, 40))
        self.horizontalLayout_5.addWidget(self.fontCB_1)
        self.font_sb1 = QSpinBox(self.tab_1)
        self.font_sb1.setMinimumSize(QSize(60, 40))
        self.font_sb1.setMinimum(1)
        self.font_sb1.setMaximum(50)
        self.font_sb1.setProperty("value", 8)
        self.horizontalLayout_5.addWidget(self.font_sb1)
        self.formLayout.setLayout(0, QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setSpacing(5)
        self.fontCB_5 = QFontComboBox(self.tab_1)
        self.fontCB_5.setMinimumSize(QSize(0, 40))
        self.horizontalLayout_6.addWidget(self.fontCB_5)
        self.font_sb5 = QSpinBox(self.tab_1)
        self.font_sb5.setMinimumSize(QSize(60, 40))
        self.font_sb5.setMinimum(1)
        self.font_sb5.setMaximum(50)
        self.font_sb5.setProperty("value", 9)
        self.horizontalLayout_6.addWidget(self.font_sb5)
        self.formLayout.setLayout(4, QFormLayout.FieldRole, self.horizontalLayout_6)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setSpacing(5)
        self.fontCB_6 = QFontComboBox(self.tab_1)
        self.fontCB_6.setMinimumSize(QSize(0, 40))
        self.horizontalLayout_7.addWidget(self.fontCB_6)
        self.font_sb6 = QSpinBox(self.tab_1)
        self.font_sb6.setMinimumSize(QSize(60, 40))
        self.font_sb6.setMinimum(1)
        self.font_sb6.setMaximum(50)
        self.font_sb6.setProperty("value", 8)
        self.horizontalLayout_7.addWidget(self.font_sb6)
        self.formLayout.setLayout(5, QFormLayout.FieldRole, self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout.setSpacing(0)
        self.frame = QFrame(self.tab_1)
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Plain)
        self.frame.setLineWidth(-2)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QFrame(self.tab_1)
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.frame_2.setLineWidth(-2)
        self.horizontalLayout.addWidget(self.frame_2)
        self.pushButton_3 = QPushButton(self.tab_1)
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QPushButton(self.tab_1)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.verticalLayout_3 = QVBoxLayout(self.tab_2)
        self.formLayout_2 = QFormLayout()
        self.lineEdit_2 = QLineEdit(self.tab_2)
        self.lineEdit_2.setMinimumSize(QSize(0, 30))
        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.lineEdit_2)
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setMinimumSize(QSize(140, 25))
        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.label_2)
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setMinimumSize(QSize(140, 25))
        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.label_3)
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setMinimumSize(QSize(140, 25))
        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.label_4)
        self.lineEdit_4 = QLineEdit(self.tab_2)
        self.lineEdit_4.setMinimumSize(QSize(0, 30))
        self.formLayout_2.setWidget(2, QFormLayout.FieldRole, self.lineEdit_4)
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setMinimumSize(QSize(140, 25))
        self.formLayout_2.setWidget(3, QFormLayout.LabelRole, self.label_5)
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setMinimumSize(QSize(140, 25))
        self.formLayout_2.setWidget(4, QFormLayout.LabelRole, self.label_6)
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setMinimumSize(QSize(140, 25))
        self.formLayout_2.setWidget(5, QFormLayout.LabelRole, self.label_7)
        self.lineEdit_5 = QLineEdit(self.tab_2)
        self.lineEdit_5.setMinimumSize(QSize(0, 30))
        self.formLayout_2.setWidget(3, QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QLineEdit(self.tab_2)
        self.lineEdit_6.setMinimumSize(QSize(0, 30))
        self.formLayout_2.setWidget(4, QFormLayout.FieldRole, self.lineEdit_6)
        self.lineEdit_7 = QLineEdit(self.tab_2)
        self.lineEdit_7.setMinimumSize(QSize(0, 30))
        self.formLayout_2.setWidget(5, QFormLayout.FieldRole, self.lineEdit_7)
        self.lineEdit_8 = QLineEdit(self.tab_2)
        self.lineEdit_8.setMinimumSize(QSize(0, 30))
        self.formLayout_2.setWidget(6, QFormLayout.FieldRole, self.lineEdit_8)
        self.label_8 = QLabel(self.tab_2)
        self.label_8.setMinimumSize(QSize(140, 25))
        self.formLayout_2.setWidget(6, QFormLayout.LabelRole, self.label_8)
        self.lineEdit_3 = QLineEdit(self.tab_2)
        self.lineEdit_3.setMinimumSize(QSize(0, 30))
        self.lineEdit_3.setMaxLength(32766)
        self.formLayout_2.setWidget(1, QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_9 = QLineEdit(self.tab_2)
        self.lineEdit_9.setMinimumSize(QSize(0, 25))
        self.formLayout_2.setWidget(7, QFormLayout.FieldRole, self.lineEdit_9)
        self.lineEdit_1 = QLineEdit(self.tab_2)
        self.lineEdit_1.setMinimumSize(QSize(0, 25))
        self.formLayout_2.setWidget(8, QFormLayout.FieldRole, self.lineEdit_1)
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setMinimumSize(QSize(140, 25))
        self.formLayout_2.setWidget(7, QFormLayout.LabelRole, self.label_9)
        self.label_1 = QLabel(self.tab_2)
        self.label_1.setMinimumSize(QSize(140, 25))
        self.formLayout_2.setWidget(8, QFormLayout.LabelRole, self.label_1)
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setMinimumSize(QSize(140, 25))
        self.formLayout_2.setWidget(9, QFormLayout.LabelRole, self.label_11)
        self.lineEdit_11 = QLineEdit(self.tab_2)
        self.lineEdit_11.setMinimumSize(QSize(140, 25))
        self.formLayout_2.setWidget(9, QFormLayout.FieldRole, self.lineEdit_11)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_8.setSpacing(0)
        self.frame_3 = QFrame(self.tab_2)
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_8.addWidget(self.frame_3)
        self.frame_4 = QFrame(self.tab_2)
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_8.addWidget(self.frame_4)
        self.pushButton_6 = QPushButton(self.tab_2)
        self.pushButton_6.setAutoDefault(True)
        self.pushButton_6.setDefault(True)
        self.horizontalLayout_8.addWidget(self.pushButton_6)
        self.pushButton_7 = QPushButton(self.tab_2)
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_7.setDefault(False)
        self.horizontalLayout_8.addWidget(self.pushButton_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.listWidget.addItem("Список\nList of")
        self.listWidget.addItem("Правил\nRules")
        self.listWidget_2.addItem("Список\nList of")
        self.listWidget_2.addItem("Цветов\nColors")
        self.retranslatei()
        self.tabWidget.setCurrentIndex(0)
        self.listWidget.setCurrentRow(-1)
        self.listWidget_2.setCurrentRow(-1)
        QMetaObject.connectSlotsByName(self)

    def retranslatei(self):
        self.setWindowTitle("Настройки")
        self.lineEdit.setText("Поле для ввода")
        self.lineEdit.setPlaceholderText("Поле для ввода")
        self.Button.setText("Кнопка")
        self.label.setText("Надпись")
        self.pushButton_3.setText("Применить")
        self.pushButton_2.setText("Отмена")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), "Шрифты")
        self.lineEdit_2.setPlaceholderText("введите ключевой символ (стандарт \"F\")")
        self.label_2.setText("Вперед")
        self.label_3.setText("Назад")
        self.label_4.setText("Влево")
        self.lineEdit_4.setPlaceholderText("введите ключевой символ (стандарт \"L\")")
        self.label_5.setText("Направо")
        self.label_6.setText("Перемещение вперед")
        self.label_7.setText("Перемещение назад")
        self.lineEdit_5.setPlaceholderText("введите ключевой символ (стандарт \"R\")")
        self.lineEdit_6.setPlaceholderText("введите ключевой символ (стандарт \"V\")")
        self.lineEdit_7.setPlaceholderText("введите ключевой символ (стандарт \"N\")")
        self.lineEdit_8.setPlaceholderText("введите ключевой символ (стандарт \"C\")")
        self.label_8.setText("Смена цвета")
        self.lineEdit_3.setPlaceholderText("введите ключевой символ (стандарт \"B\")")
        self.lineEdit_9.setPlaceholderText("введите ключевой симдол (стандарт \"S\")")
        self.lineEdit_1.setPlaceholderText("введите ключевой символ (стандарт \"E\")")
        self.lineEdit_11.setPlaceholderText("введите ключевой символ (стандарт \"T\")")
        self.label_9.setText("Квадрат")
        self.label_1.setText("Круг")
        self.label_11.setText("Треугольник")
        self.pushButton_6.setText("Применить")
        self.pushButton_7.setText("Отмена")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), "Обозначения")
        self.listWidget.setFont(self.fnt_fr_rlw)
        self.listWidget_2.setFont(self.fnt_fr_clw)
        self.lineEdit.setFont(self.fnt_for_le)
        self.Button.setFont(self.fnt_fr_btn)
        self.label.setFont(self.fnt_for_lb)
        self.label_2.setFont(self.fnt_for_lb)
        self.label_3.setFont(self.fnt_for_lb)
        self.label_4.setFont(self.fnt_for_lb)
        self.label_5.setFont(self.fnt_for_lb)
        self.label_6.setFont(self.fnt_for_lb)
        self.label_7.setFont(self.fnt_for_lb)
        self.label_8.setFont(self.fnt_for_lb)
        self.label_9.setFont(self.fnt_for_lb)
        self.label_1.setFont(self.fnt_for_lb)
        self.func()

    def func(self):
        self.pushButton_6.clicked.connect(self.acept)
        self.pushButton_7.clicked.connect(self.rest)
        self.pushButton_2.clicked.connect(self.rest2)
        self.pushButton_3.clicked.connect(self.acept2)
        self.font_sb1.valueChanged.connect(self.spin)
        self.font_sb2.valueChanged.connect(self.spin)
        self.font_sb3.valueChanged.connect(self.spin)
        self.font_sb4.valueChanged.connect(self.spin)
        self.font_sb5.valueChanged.connect(self.spin)
        self.font_sb6.valueChanged.connect(self.spin)
        self.fontCB_3.currentFontChanged.connect(self.spin)
        self.fontCB_4.currentFontChanged.connect(self.spin)
        self.fontCB_5.currentFontChanged.connect(self.spin)
        self.fontCB_6.currentFontChanged.connect(self.spin)
        self.fontCB_2.currentFontChanged.connect(self.spin)
        self.fontCB_1.currentFontChanged.connect(self.spin)
        self.rest2()

    def acept(self):
        if len(self.lineEdit_2.text()) > 0:
            self.forw = self.lineEdit_2.text()
        if len(self.lineEdit_3.text()) > 0:
            self.back = self.lineEdit_3.text()
        if len(self.lineEdit_4.text()) > 0:
            self.left = self.lineEdit_4.text()
        if len(self.lineEdit_5.text()) > 0:
            self.righ = self.lineEdit_5.text()
        if len(self.lineEdit_6.text()) > 0:
            self.vfor = self.lineEdit_6.text()
        if len(self.lineEdit_7.text()) > 0:
            self.vbac = self.lineEdit_7.text()
        if len(self.lineEdit_8.text()) > 0:
            self.colb = self.lineEdit_8.text()
        if len(self.lineEdit_9.text()) > 0:
            self.scvr = self.lineEdit_9.text()
        if len(self.lineEdit_1.text()) > 0:
            self.circ = self.lineEdit_1.text()
        if len(self.lineEdit_11.text()) > 0:
            self.tria = self.lineEdit_11.text()

    def acept2(self):
        f = QFont(self.fontCB_2.font().family(), self.font_sb2.value())
        self.lineEdit_2.setFont(f)
        self.lineEdit_3.setFont(f)
        self.lineEdit_4.setFont(f)
        self.lineEdit_5.setFont(f)
        self.lineEdit_6.setFont(f)
        self.lineEdit_7.setFont(f)
        self.lineEdit_8.setFont(f)
        self.lineEdit_9.setFont(f)
        self.lineEdit_1.setFont(f)
        self.lineEdit_11.setFont(f)
        self.fnt_for_sb = QFont(self.fontCB_1.font().family(), self.font_sb1.value())
        self.fnt_for_le = QFont(self.fontCB_2.font().family(), self.font_sb2.value())
        self.fnt_for_lb = QFont(self.fontCB_3.font().family(), self.font_sb3.value())
        self.fnt_fr_rlw = QFont(self.fontCB_4.font().family(), self.font_sb4.value())
        self.fnt_fr_clw = QFont(self.fontCB_5.font().family(), self.font_sb5.value())
        self.fnt_fr_btn = QFont(self.fontCB_6.font().family(), self.font_sb6.value())

    def rest(self):
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        self.lineEdit_7.clear()
        self.lineEdit_8.clear()
        self.lineEdit_9.clear()
        self.lineEdit_1.clear()
        self.lineEdit_11.clear()
        self.forw = "F"
        self.back = "B"
        self.left = "L"
        self.righ = "R"
        self.vfor = "V"
        self.vbac = "N"
        self.colb = "C"
        self.scvr = "S"
        self.circ = "E"
        self.tria = "T"

    def rest2(self):
        f1 = self.fnt_for_sb
        f2 = self.fnt_for_le
        f3 = self.fnt_for_lb
        f4 = self.fnt_fr_rlw
        f5 = self.fnt_fr_clw
        f6 = self.fnt_fr_btn
        self.font_sb1.setValue(f1.pointSize())
        self.font_sb2.setValue(f2.pointSize())
        self.font_sb3.setValue(f3.pointSize())
        self.font_sb4.setValue(f4.pointSize())
        self.font_sb5.setValue(f5.pointSize())
        self.font_sb6.setValue(f6.pointSize())
        self.fontCB_1.setCurrentFont(f1)
        self.fontCB_2.setCurrentFont(f2)
        self.fontCB_3.setCurrentFont(f3)
        self.fontCB_4.setCurrentFont(f4)
        self.fontCB_5.setCurrentFont(f5)
        self.fontCB_6.setCurrentFont(f6)
        self.acept2()

    def spin(self):
        f = QFont()
        f.setPointSize(self.font_sb1.value())
        f.setFamily(self.fontCB_1.currentText())
        self.spinBox.setFont(f)
        self.fontCB_1.setFont(f)
        f.setPointSize(self.font_sb2.value())
        f.setFamily(self.fontCB_2.currentText())
        self.lineEdit.setFont(f)
        self.fontCB_2.setFont(f)
        f.setPointSize(self.font_sb3.value())
        f.setFamily(self.fontCB_3.currentText())
        self.fontCB_3.setFont(f)
        self.label.setFont(f)
        f.setPointSize(self.font_sb4.value())
        f.setFamily(self.fontCB_4.currentText())
        self.listWidget.setFont(f)
        self.fontCB_4.setFont(f)
        f.setPointSize(self.font_sb5.value())
        f.setFamily(self.fontCB_5.currentText())
        self.listWidget_2.setFont(f)
        self.fontCB_5.setFont(f)
        f.setPointSize(self.font_sb6.value())
        f.setFamily(self.fontCB_6.currentText())
        self.Button.setFont(f)
        self.fontCB_6.setFont(f)


if __name__ == '__main__':
    print("не написано")
